# -*- coding: utf-8 -*-
"""Project1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ViT99lgtZVhsJhCysGty40Bx-MwLyQXd
"""

!pip install scikit-learn

import sklearn
from sklearn.datasets import load_breast_cancer

#preparing the data
data = load_breast_cancer()

#organizing the data and looking at it
label_names =data['target_names']
labels = data['target']
feature_names = data['feature_names']
features = data['data']

#print all the fields
print(label_names)
print(labels)
print(feature_names)
print(features)

#organising the data into sets
from sklearn.model_selection import train_test_split

#splitting the data
train, test,train_labels,test_labels = train_test_split(features,labels,test_size = 0.33,random_state =42)

#importing the gaussian naive bayes algorithm
from sklearn.naive_bayes import GaussianNB

#initialize the classifier
gnb = GaussianNB()

#train the classifier
model = gnb.fit(train, train_labels)

#making predictions
predictions =gnb.predict(test)

#print the predictions
print(predictions)

#lets test the accuracy
#importing the accuracy measuring function
from sklearn.metrics import accuracy_score

#evaluating the accuracy
print(accuracy_score(test_labels, predictions))